name: Deploy Pelican to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.11.4'  # Укажите версию Python, которую вы используете

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican markdown  # Установите необходимые зависимости

      - name: Build the site
        run: pelican content -o output -s publishconf.py  # Укажите ваши параметры сборки

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Путь к директории с собранным сайтом
